### ISSUE TITLE
After reset, removal of a sound leads to exception

### ISSUE THREAD

**Issue by nbudzyn** [jfelkel/SoundboardCrafter#19]
- User clicks reset and confirms.
- User long-clicks a sound and clicks "Remove".

App crashes:
2019-04-01 23:02:55.548 19840-19840/de.soundboardcrafter D/AbsListView: onTouchUp() mTouchMode : 0
2019-04-01 23:02:55.625 19840-19840/de.soundboardcrafter D/de.soundboardcrafter.activity.soundboard.play.SoundboardFragment: Removing sound 1
2019-04-01 23:02:55.631 19840-20462/de.soundboardcrafter D/de.soundboardcrafter.activity.soundboard.play.SoundboardFragment$RemoveSoundsTask: Removing sound + 1 from soundboard
2019-04-01 23:02:55.638 19840-20462/de.soundboardcrafter E/AndroidRuntime: FATAL EXCEPTION: AsyncTask #6
    Process: de.soundboardcrafter, PID: 19840
    java.lang.RuntimeException: An error occurred while executing doInBackground()
        at android.os.AsyncTask$3.done(AsyncTask.java:353)
        at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:383)
        at java.util.concurrent.FutureTask.setException(FutureTask.java:252)
        at java.util.concurrent.FutureTask.run(FutureTask.java:271)
        at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:245)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
        at java.lang.Thread.run(Thread.java:764)
     Caused by: java.lang.RuntimeException: There was no sound at index 1.
        at de.soundboardcrafter.dao.SoundboardDao.unlinkSound(SoundboardDao.java:334)
        at de.soundboardcrafter.activity.soundboard.play.SoundboardFragment$RemoveSoundsTask.doInBackground(SoundboardFragment.java:370)
        at de.soundboardcrafter.activity.soundboard.play.SoundboardFragment$RemoveSoundsTask.doInBackground(SoundboardFragment.java:347)
        at android.os.AsyncTask$2.call(AsyncTask.java:333)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:245) 
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162) 
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636) 
        at java.lang.Thread.run(Thread.java:764) 

Linked to #18 ?

**Comment by nbudzyn** [comment]
Sometimes this is part of the problem:
https://stackoverflow.com/questions/9753213/wrong-fragment-in-viewpager-receives-oncontextitemselected-call
